import { parse as yamlParse, stringify as yamlStringify } from 'yaml';
import { DEFAULT_SOCKET } from '../shared/defaults.ts';
import { parseThreshold } from '../metrics/thresholds.ts';
import type { CheckSpec, RunConfig, SocketConfig, SocketFlowStep, ThresholdSpec } from '../shared/types.ts';
import { buildFlow } from '../runners/artillery.runner.ts';
import type { ImportResult } from './k6.ts';

/**
 * Artillery YAML ⇄ UI configuration.
 *
 * Almost everything in the form has a native YAML home (target, phases, ws
 * headers, flow). Only the dashboard's own concepts — check pass-rate floors,
 * the threshold DSL, round-trip measurement — need the `dashboard:` block,
 * which Artillery ignores because it only reads config/scenarios/before/after.
 */

export function toArtilleryScript(config: RunConfig): string {
  const cfg = config.socket ?? DEFAULT_SOCKET;

  // Same builder the runner uses, so an exported script cannot drift from what
  // actually runs.
  const flow = buildFlow(cfg);

  const engineConfig = cfg.engine === 'socketio'
    ? {
        socketio: {
          ...(cfg.transports.length ? { transports: cfg.transports } : {}),
          ...(Object.keys(cfg.query).length ? { query: cfg.query } : {}),
          ...(Object.keys(cfg.headers).length ? { extraHeaders: cfg.headers } : {}),
        },
      }
    : {
        ws: {
          ...(Object.keys(cfg.headers).length ? { headers: cfg.headers } : {}),
          ...(cfg.subprotocols.length ? { subprotocols: cfg.subprotocols } : {}),
        },
      };

  const doc: Record<string, unknown> = {
    config: {
      target: cfg.url,
      phases: cfg.phases.map((p) => ({
        name: p.name,
        duration: p.durationSec,
        arrivalRate: p.arrivalRate,
        ...(p.rampTo ? { rampTo: p.rampTo } : {}),
      })),
      ...engineConfig,
    },
    scenarios: [{ engine: cfg.engine, name: 'socket', flow }],
    // Ignored by Artillery; read back on import.
    dashboard: {
      protocol: 'socket',
      engine: cfg.engine,
      namespace: cfg.namespace,
      measureRoundTrip: cfg.measureRoundTrip,
      checks: config.checks,
      thresholds: config.thresholds.map((t) => t.expr),
    },
  };

  return `# Generated by Loadtest Dashboard — edit freely and import it back.\n${yamlStringify(doc)}`;
}

export function fromArtilleryScript(source: string): ImportResult {
  const warnings: string[] = [];
  let doc: Record<string, unknown> | null;
  try {
    doc = yamlParse(source) as Record<string, unknown> | null;
  } catch (err) {
    throw new Error(`not parseable YAML: ${(err as Error).message}`);
  }
  if (!doc || typeof doc !== 'object') throw new Error('YAML document is empty');

  const socket: SocketConfig = structuredClone(DEFAULT_SOCKET);
  let checks: CheckSpec[] = [];
  let thresholds: ThresholdSpec[] = [];

  const config = rec(doc.config);
  if (!config) warnings.push('no `config:` block — target and phases left at defaults');

  const target = str(config?.target);
  if (target) socket.url = target;
  else if (config) warnings.push('no `config.target` — URL left at default');

  const phases = arr(config?.phases);
  if (phases?.length) {
    const mapped: SocketConfig['phases'] = [];
    for (const [i, raw] of phases.entries()) {
      const p = rec(raw);
      if (!p) continue;
      const durationSec = num(p.duration);
      const arrivalRate = num(p.arrivalRate);
      if (durationSec === null) { warnings.push(`phase ${i + 1} has no numeric duration — skipped`); continue; }
      if (arrivalRate === null && num(p.arrivalCount) === null) {
        warnings.push(`phase ${i + 1} uses an arrival model the form cannot represent — skipped`);
        continue;
      }
      mapped.push({
        name: str(p.name) ?? `phase ${i + 1}`,
        durationSec,
        arrivalRate: arrivalRate ?? num(p.arrivalCount) ?? 1,
        rampTo: num(p.rampTo) ?? undefined,
      });
    }
    if (mapped.length) socket.phases = mapped;
  }

  const ws = rec(config?.ws);
  if (ws) {
    const headers = strRecord(rec(ws.headers));
    if (headers) socket.headers = headers;
    const subs = arr(ws.subprotocols);
    if (subs) socket.subprotocols = subs.filter((x): x is string => typeof x === 'string');
  }

  const scenarios = arr(doc.scenarios);
  const scenario = scenarios?.map(rec).find((s) => s !== null) ?? null;
  if (!scenario) {
    warnings.push('no scenarios found — flow left at defaults');
  } else {
    const engine = str(scenario.engine);
    if (engine === 'socketio' || engine === 'socket.io') socket.engine = 'socketio';
    else if (engine === 'ws' || !engine) socket.engine = 'ws';
    else warnings.push(`scenario engine "${engine}" is not supported — falling back to the ws engine`);
    if (scenarios && scenarios.length > 1) {
      warnings.push(`${scenarios.length} scenarios found — only the first is shown in the form`);
    }
    const flow = arr(scenario.flow);
    if (flow) {
      const steps: SocketFlowStep[] = [];
      for (const raw of flow) {
        const step = rec(raw);
        if (!step) continue;
        if ('emit' in step) {
          const emit = rec(step.emit);
          const data = emit?.data;
          steps.push({
            kind: 'emit',
            event: str(emit?.channel) ?? '',
            value: typeof data === 'string' ? data : JSON.stringify(data ?? ''),
            acknowledge: 'acknowledge' in step,
            ...readMatch(rec(step.acknowledge)),
            ...(str(step.namespace) ? { namespace: str(step.namespace)! } : {}),
          });
          const resp = rec(step.response);
          if (resp) {
            const channel = str(resp.channel) ?? str(resp.on) ?? '?';
            warnings.push(
              `waiting on server event "${channel}" is not supported: the engine reports a flat ~10s `
              + 'response time regardless of arrival, and it cannot be combined with an acknowledgement — dropped',
            );
          }
        } else if ('send' in step) {
          const sendObj = rec(step.send);
          const payload = sendObj ? sendObj.payload : step.send;
          const value = typeof payload === 'string' ? payload : JSON.stringify(payload ?? '');
          steps.push({ kind: 'send', value });
          // match lives inside `send`; `response.match` is the older shape.
          const match = rec(sendObj?.match) ?? rec(rec(step.response)?.match);
          const expected = str(match?.regexp) ?? str(match?.value) ?? str(match?.json);
          if (expected) steps.push({ kind: 'expect', value: unescapeRegex(expected) });
        } else if ('think' in step) {
          steps.push({ kind: 'think', value: String(num(step.think) ?? 1) });
        } else {
          warnings.push(`flow step ${JSON.stringify(step).slice(0, 60)} has no form equivalent — dropped`);
        }
      }
      if (steps.length) socket.flow = steps;
    }
  }

  const socketioCfg = rec(config?.socketio);
  if (socketioCfg) {
    socket.engine = 'socketio';
    const transports = arr(socketioCfg.transports);
    if (transports) socket.transports = transports.filter((x): x is string => typeof x === 'string');
    const query = strRecord(rec(socketioCfg.query));
    if (query) socket.query = query;
    const extra = strRecord(rec(socketioCfg.extraHeaders));
    if (extra) socket.headers = extra;
  }

  const meta = rec(doc.dashboard);
  if (meta) {
    const engine = str(meta.engine);
    if (engine === 'ws' || engine === 'socketio') socket.engine = engine;
    const ns = str(meta.namespace);
    if (ns !== null) socket.namespace = ns;
    const rtt = meta.measureRoundTrip;
    if (typeof rtt === 'boolean') socket.measureRoundTrip = rtt;
    checks = readChecks(arr(meta.checks), warnings);
    const exprs = arr(meta.thresholds);
    if (exprs) {
      for (const e of exprs) {
        if (typeof e !== 'string') continue;
        if (parseThreshold(e)) thresholds.push({ expr: e });
        else warnings.push(`threshold "${e}" is not valid DSL — dropped`);
      }
    }
  }

  // Artillery's own `ensure` block is the closest native equivalent to thresholds.
  const ensure = rec(config?.ensure);
  if (ensure && thresholds.length === 0) {
    for (const [key, raw] of Object.entries(ensure)) {
      const v = num(raw);
      if (key === 'maxErrorRate' && v !== null) thresholds.push({ expr: `error_rate < ${v}` });
      else if (key === 'p95' && v !== null) thresholds.push({ expr: `p95 < ${v}` });
      else if (key === 'p99' && v !== null) thresholds.push({ expr: `p99 < ${v}` });
      else if (key === 'median' || key === 'max' || key === 'min') {
        if (v !== null && key !== 'median') thresholds.push({ expr: `${key} < ${v}` });
        else warnings.push(`ensure.${key} has no DSL equivalent — dropped`);
      } else {
        warnings.push(`ensure.${key} has no DSL equivalent — dropped`);
      }
    }
  }

  // The exporter stamps the connection namespace onto every step; reading it
  // back as a per-step override would rewrite the flow on every round trip.
  for (const step of socket.flow) {
    if (step.namespace && step.namespace === socket.namespace) delete step.namespace;
  }

  return {
    config: { protocol: 'socket', socket, checks, thresholds, script: { mode: 'builtin', content: '', path: '', filename: '' } },
    warnings,
  };
}

/** Pull `match: { json, value }` back into the flat step fields the form uses. */
function readMatch(spec: Record<string, unknown> | null): Partial<SocketFlowStep> {
  const match = rec(spec?.match);
  if (!match) return {};
  const path = str(match.json) ?? str(match.jsonpath);
  if (!path) return {};
  return { matchPath: denormalizeJsonPath(path), matchValue: str(match.value) ?? '' };
}

/**
 * Inverse of the runner's normalizeJsonPath: the YAML addresses the ack
 * argument array, the form shows the path into the payload. Without this a
 * round-trip rewrites what the user typed.
 */
function denormalizeJsonPath(path: string): string {
  const p = path.trim();
  if (p === '$[0]') return '$';
  return p.startsWith('$[0].') ? `$.${p.slice('$[0].'.length)}` : p;
}

function readChecks(list: unknown[] | null, warnings: string[]): CheckSpec[] {
  if (!list) return [];
  const out: CheckSpec[] = [];
  for (const raw of list) {
    const c = rec(raw);
    const name = str(c?.name);
    const kind = str(c?.kind);
    if (!c || !name || !kind) continue;
    if (!['status', 'body_contains', 'json_path', 'regex', 'latency_under'].includes(kind)) {
      warnings.push(`check "${name}" has unknown kind "${kind}" — dropped`);
      continue;
    }
    out.push({
      name,
      kind: kind as CheckSpec['kind'],
      value: str(c.value) ?? String(num(c.value) ?? ''),
      path: str(c.path) ?? undefined,
      minPassRatePct: num(c.minPassRatePct) ?? undefined,
    });
  }
  return out;
}

function isRecord(v: unknown): boolean {
  return !!v && typeof v === 'object' && !Array.isArray(v);
}

function rec(v: unknown): Record<string, unknown> | null {
  return v && typeof v === 'object' && !Array.isArray(v) ? (v as Record<string, unknown>) : null;
}
function arr(v: unknown): unknown[] | null { return Array.isArray(v) ? v : null; }
function str(v: unknown): string | null { return typeof v === 'string' ? v : null; }
function num(v: unknown): number | null {
  if (typeof v === 'number' && Number.isFinite(v)) return v;
  if (typeof v === 'string' && v.trim() !== '' && Number.isFinite(Number(v))) return Number(v);
  return null;
}
function strRecord(r: Record<string, unknown> | null): Record<string, string> | null {
  if (!r) return null;
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(r)) {
    if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') out[k] = String(v);
  }
  return out;
}

function escapeRegex(s: string): string { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
function unescapeRegex(s: string): string { return s.replace(/\\([.*+?^${}()|[\]\\])/g, '$1'); }
