import { parse } from 'acorn';
import type * as ESTree from 'acorn';
import { DEFAULT_REST } from '../shared/defaults.ts';
import { parseThreshold, toK6Thresholds } from '../metrics/thresholds.ts';
import {
  asArray, asBool, asNumber, asRecord, asString, propertyName, staticValue, toSeconds,
  UNRESOLVED, type Static,
} from './literal.ts';
import type { CheckSpec, RestConfig, RunConfig, ThresholdSpec } from '../shared/types.ts';

/**
 * k6 script ⇄ UI configuration.
 *
 * Export writes a script whose checks use named helpers, so the importer can
 * recognise them structurally instead of trying to understand arbitrary
 * predicates. A `dashboard` metadata export carries the few fields k6 has no
 * equivalent for (body type, auth kind, per-check minimum pass rate).
 *
 * Foreign scripts — anything not produced here — still import: the parser falls
 * back to reading `options`, the http call and any check predicates it
 * recognises, and reports the rest as warnings rather than silently dropping it.
 */

/** k6's default HTTP request timeout when `params.timeout` is absent. */
const K6_DEFAULT_TIMEOUT_SEC = 60;

// ─── Export ──────────────────────────────────────────────────────────────────

export function toK6Script(config: RunConfig): string {
  const cfg = config.rest ?? DEFAULT_REST;
  const { thresholds, unmapped } = toK6Thresholds(config.thresholds);

  const options: Record<string, unknown> = {};
  if (cfg.loadModel === 'vus') {
    options.vus = cfg.vus;
    options.duration = `${cfg.vusDurationSec}s`;
  } else if (cfg.loadModel === 'rate') {
    options.scenarios = {
      constant_rate: {
        executor: 'constant-arrival-rate',
        rate: cfg.rate,
        timeUnit: '1s',
        duration: `${cfg.rateDurationSec}s`,
        preAllocatedVUs: cfg.preAllocatedVUs,
        maxVUs: Math.max(cfg.preAllocatedVUs * 4, cfg.rate),
      },
    };
  } else {
    options.stages = cfg.stages.map((s) => ({ duration: `${s.duration}s`, target: s.target }));
  }
  if (Object.keys(thresholds).length) options.thresholds = thresholds;
  if (cfg.insecureSkipTlsVerify) options.insecureSkipTLSVerify = true;
  options.summaryTrendStats = ['min', 'avg', 'p(90)', 'p(95)', 'p(99)', 'max'];

  const headers = { ...cfg.headers };
  if (cfg.bodyType === 'json' && !hasHeader(headers, 'content-type')) headers['Content-Type'] = 'application/json';
  if (cfg.bodyType === 'form' && !hasHeader(headers, 'content-type')) headers['Content-Type'] = 'application/x-www-form-urlencoded';

  const meta = {
    protocol: 'rest',
    bodyType: cfg.bodyType,
    // The exported params inject Content-Type so the script works standalone;
    // keeping the originals here means a round-trip does not grow a header the
    // user never typed.
    headers: cfg.headers,
    auth: cfg.auth,
    thinkTimeMs: cfg.thinkTimeMs,
    checks: config.checks,
    thresholds: config.thresholds.map((x) => x.expr),
  };

  const lines: string[] = [];
  lines.push('// Generated by Loadtest Dashboard — edit freely and import it back.');
  if (unmapped.length) {
    lines.push('//');
    lines.push('// These thresholds have no k6 equivalent and are evaluated by the');
    lines.push('// dashboard on the collected metrics instead:');
    for (const u of unmapped) lines.push(`//   ${u}`);
  }
  lines.push("import http from 'k6/http';");
  lines.push("import { check, sleep } from 'k6';");
  lines.push('');
  lines.push(`export const options = ${json(options, 0)};`);
  lines.push('');
  lines.push('// Round-trip metadata for the dashboard form. Deleting it only means');
  lines.push('// those fields fall back to defaults on the next import.');
  lines.push(`export const dashboard = ${json(meta, 0)};`);
  lines.push('');
  lines.push(HELPERS);
  lines.push('');
  lines.push(`const url = ${str(cfg.url)};`);
  lines.push(`const params = {`);
  lines.push(`  headers: ${json(headers, 1)},`);
  lines.push(`  timeout: ${str(`${cfg.timeoutSec}s`)},`);
  lines.push(`  redirects: ${cfg.followRedirects ? 10 : 0},`);
  lines.push('};');
  lines.push(`const body = ${cfg.bodyType === 'none' || !cfg.body ? 'null' : str(cfg.body)};`);
  lines.push('');
  lines.push('export default function () {');
  lines.push(`  const res = http.request(${str(cfg.method)}, url, body, params);`);
  if (config.checks.length) {
    lines.push('  check(res, {');
    for (const c of config.checks) lines.push(`    ${str(c.name)}: (r) => ${checkExpr(c)},`);
    lines.push('  });');
  }
  if (cfg.thinkTimeMs > 0) lines.push(`  sleep(${cfg.thinkTimeMs / 1000});`);
  lines.push('}');
  lines.push('');
  lines.push('export function handleSummary(data) {');
  lines.push('  const out = {};');
  lines.push('  out[__ENV.SUMMARY_OUT] = JSON.stringify(data);');
  lines.push('  return out;');
  lines.push('}');
  return lines.join('\n') + '\n';
}

const HELPERS = `// Helpers the dashboard recognises when importing this file back.
function matchStatus(status, spec) {
  const parts = String(spec).split(/[|,]/);
  for (let i = 0; i < parts.length; i++) {
    const p = parts[i].trim();
    if (!p) continue;
    const range = /^([1-5]\\d{2})\\s*-\\s*([1-5]\\d{2})$/.exec(p);
    if (range && status >= +range[1] && status <= +range[2]) return true;
    const wild = /^([1-5])[xX]{2}$/.exec(p);
    if (wild && status >= +wild[1] * 100 && status <= +wild[1] * 100 + 99) return true;
    if (/^[1-5]\\d{2}$/.test(p) && status === +p) return true;
  }
  return false;
}

function jsonPath(obj, path) {
  let cur = obj;
  const parts = String(path).split('.');
  for (let i = 0; i < parts.length; i++) {
    if (cur == null) return undefined;
    cur = cur[parts[i]];
  }
  return cur;
}`;

function checkExpr(c: CheckSpec): string {
  switch (c.kind) {
    case 'status': return `matchStatus(r.status, ${str(c.value)})`;
    case 'body_contains': return `String(r.body || '').includes(${str(c.value)})`;
    case 'regex': return `new RegExp(${str(c.value)}).test(String(r.body || ''))`;
    case 'json_path': return `String(jsonPath(r.json(), ${str(c.path ?? '')})) === ${str(c.value)}`;
    case 'latency_under': return `r.timings.duration < ${Number(c.value) || 0}`;
  }
}

// ─── Import ──────────────────────────────────────────────────────────────────

export interface ImportResult {
  config: RunConfig;
  warnings: string[];
}

export function fromK6Script(source: string): ImportResult {
  const warnings: string[] = [];
  let ast: ESTree.Program;
  try {
    ast = parse(source, { ecmaVersion: 2022, sourceType: 'module' });
  } catch (err) {
    throw new Error(`not a parseable JavaScript module: ${(err as Error).message}`);
  }

  const rest: RestConfig = structuredClone(DEFAULT_REST);
  let checks: CheckSpec[] = [];
  let thresholds: ThresholdSpec[] = [];

  const exported = collectExportedObjects(ast);

  // 1. Metadata block, when the file came from here.
  const meta = exported.get('dashboard');
  if (meta) {
    const bodyType = asString(meta.bodyType);
    if (bodyType && ['none', 'json', 'raw', 'form'].includes(bodyType)) {
      rest.bodyType = bodyType as RestConfig['bodyType'];
    }
    const auth = asRecord(meta.auth);
    if (auth) {
      const kind = asString(auth.kind);
      if (kind === 'none' || kind === 'basic' || kind === 'bearer') {
        rest.auth = {
          kind,
          username: asString(auth.username) ?? undefined,
          password: asString(auth.password) ?? undefined,
          token: asString(auth.token) ?? undefined,
        };
      }
    }
    const think = asNumber(meta.thinkTimeMs);
    if (think !== null) rest.thinkTimeMs = think;
    const metaHeaders = stringRecord(asRecord(meta.headers));
    if (metaHeaders) rest.headers = metaHeaders;
    checks = readMetaChecks(asArray(meta.checks));
    const exprs = asArray(meta.thresholds);
    if (exprs) {
      thresholds = exprs.filter((e): e is string => typeof e === 'string').map((expr) => ({ expr }));
    }
  }

  // 2. options — load model, thresholds, TLS.
  const options = exported.get('options');
  if (options) {
    applyOptions(options, rest, warnings, (t) => { if (!thresholds.length) thresholds = t; });
  } else {
    warnings.push('no `export const options` found — load model left at defaults');
  }

  // 3. The request itself.
  const req = findHttpCall(ast, source);
  if (req) {
    if (req.method) rest.method = req.method;
    if (req.url) rest.url = req.url;
    // Metadata headers, when present, are the user's originals — do not let the
    // script's effective headers (which include injected ones) overwrite them.
    if (req.headers && !meta) rest.headers = req.headers;
    // No explicit timeout means k6's own default (60s), not this form's default.
    // Carrying the form default over would quietly halve the timeout on import.
    rest.timeoutSec = req.timeoutSec ?? K6_DEFAULT_TIMEOUT_SEC;
    if (req.redirects !== null) rest.followRedirects = req.redirects > 0;
    if (req.body !== undefined) {
      rest.body = req.body ?? '';
      if (rest.bodyType === 'none' && req.body) rest.bodyType = looksJson(req.body) ? 'json' : 'raw';
    }
    if (req.unresolved.length) {
      warnings.push(`request values not statically resolvable: ${req.unresolved.join(', ')}`);
    }
  } else {
    warnings.push('no http.request / http.get / http.post call found — target URL left at default');
  }

  // 4. sleep() as think time, when metadata did not already supply it.
  if (!meta) {
    const slept = findSleepSeconds(ast);
    if (slept !== null) rest.thinkTimeMs = Math.round(slept * 1000);
  }

  // 5. Checks from predicates, for scripts that carry no metadata.
  if (checks.length === 0) {
    const parsed = parseChecks(ast, source);
    checks = parsed.checks;
    warnings.push(...parsed.warnings);
  }

  return {
    config: { protocol: 'rest', rest, checks, thresholds, script: { mode: 'builtin', content: '', path: '', filename: '' } },
    warnings,
  };
}

function readMetaChecks(arr: Static[] | null): CheckSpec[] {
  if (!arr) return [];
  const out: CheckSpec[] = [];
  for (const item of arr) {
    const r = asRecord(item);
    if (!r) continue;
    const name = asString(r.name);
    const kind = asString(r.kind);
    if (!name || !kind) continue;
    if (!['status', 'body_contains', 'json_path', 'regex', 'latency_under'].includes(kind)) continue;
    out.push({
      name,
      kind: kind as CheckSpec['kind'],
      value: asString(r.value) ?? String(asNumber(r.value) ?? ''),
      path: asString(r.path) ?? undefined,
      minPassRatePct: asNumber(r.minPassRatePct) ?? undefined,
    });
  }
  return out;
}

function applyOptions(
  options: Record<string, Static>,
  rest: RestConfig,
  warnings: string[],
  setThresholds: (t: ThresholdSpec[]) => void,
): void {
  const tls = asBool(options.insecureSkipTLSVerify);
  if (tls !== null) rest.insecureSkipTlsVerify = tls;

  const scenarios = asRecord(options.scenarios);
  const stages = asArray(options.stages);
  const plainVus = asNumber(options.vus);
  const plainDuration = toSeconds(options.duration);

  if (scenarios) {
    const first = Object.values(scenarios).map(asRecord).find((s) => s !== null);
    const executor = first ? asString(first.executor) : null;
    if (first && executor && executor.includes('arrival-rate')) {
      rest.loadModel = 'rate';
      rest.rate = asNumber(first.rate) ?? rest.rate;
      rest.rateDurationSec = toSeconds(first.duration) ?? rest.rateDurationSec;
      rest.preAllocatedVUs = asNumber(first.preAllocatedVUs) ?? rest.preAllocatedVUs;
    } else if (first && executor === 'ramping-vus') {
      rest.loadModel = 'stages';
      const st = readStages(asArray(first.stages));
      if (st.length) rest.stages = st;
    } else {
      warnings.push(`scenario executor "${executor ?? 'unknown'}" has no form equivalent — load model left at defaults`);
    }
  } else if (stages) {
    rest.loadModel = 'stages';
    const st = readStages(stages);
    if (st.length) rest.stages = st;
  } else if (plainVus !== null || plainDuration !== null) {
    // The most common k6 shape: a fixed VU count for a fixed duration.
    rest.loadModel = 'vus';
    if (plainVus !== null) rest.vus = plainVus;
    if (plainDuration !== null) rest.vusDurationSec = plainDuration;
    if (plainVus === null) warnings.push('`duration` without `vus` — VU count left at default');
    if (plainDuration === null) warnings.push('`vus` without `duration` — duration left at default');
  } else {
    warnings.push('options declares no vus/duration, stages or scenarios — load model left at defaults');
  }

  const th = asRecord(options.thresholds);
  if (th) {
    const specs = fromK6Thresholds(th, warnings);
    if (specs.length) setThresholds(specs);
  }
}

function readStages(arr: Static[] | null): Array<{ duration: number; target: number }> {
  if (!arr) return [];
  const out: Array<{ duration: number; target: number }> = [];
  for (const s of arr) {
    const r = asRecord(s);
    if (!r) continue;
    const duration = toSeconds(r.duration);
    const target = asNumber(r.target);
    if (duration === null || target === null) continue;
    out.push({ duration, target });
  }
  return out;
}

/** Reverse of toK6Thresholds. Anything unrecognised is reported, not dropped silently. */
export function fromK6Thresholds(th: Record<string, Static>, warnings: string[]): ThresholdSpec[] {
  const out: ThresholdSpec[] = [];
  for (const [metric, raw] of Object.entries(th)) {
    const conds = Array.isArray(raw) ? raw : [raw];
    for (const cond of conds) {
      const expr = typeof cond === 'string' ? cond : asString(asRecord(cond)?.threshold);
      if (!expr) { warnings.push(`threshold on ${metric} is not a plain string`); continue; }
      const mapped = mapK6Threshold(metric, expr);
      if (mapped) out.push({ expr: mapped });
      else warnings.push(`threshold "${metric}: ${expr}" has no DSL equivalent`);
    }
  }
  return out;
}

function mapK6Threshold(metric: string, expr: string): string | null {
  const m = /^\s*([a-z()0-9]+)\s*(<=|>=|<|>|==|!=)\s*(-?[0-9]*\.?[0-9]+)\s*$/i.exec(expr);
  if (!m) return null;
  const [, stat, op, num] = m;
  const value = Number(num);

  if (metric === 'http_req_duration') {
    const s = stat.toLowerCase();
    const name = s === 'p(90)' ? 'p90' : s === 'p(95)' ? 'p95' : s === 'p(99)' ? 'p99'
      : s === 'min' || s === 'avg' || s === 'max' || s === 'med' ? (s === 'med' ? null : s) : null;
    return name ? `${name} ${op} ${value}` : null;
  }
  if (metric === 'http_req_failed' && stat.toLowerCase() === 'rate') {
    // k6 rate is 0..1; the DSL speaks percent.
    return `error_rate ${op} ${round4(value * 100)}`;
  }
  if (metric === 'http_reqs' && stat.toLowerCase() === 'rate') {
    return `rps ${op} ${value}`;
  }
  return null;
}

// ─── AST helpers ─────────────────────────────────────────────────────────────

/** `export const <name> = { ... }` → static object, for options and dashboard. */
function collectExportedObjects(ast: ESTree.Program): Map<string, Record<string, Static>> {
  const out = new Map<string, Record<string, Static>>();
  for (const node of ast.body) {
    if (node.type !== 'ExportNamedDeclaration' || !node.declaration) continue;
    if (node.declaration.type !== 'VariableDeclaration') continue;
    for (const decl of node.declaration.declarations) {
      if (decl.id.type !== 'Identifier' || !decl.init) continue;
      const value = asRecord(staticValue(decl.init));
      if (value) out.set(decl.id.name, value);
    }
  }
  return out;
}

interface HttpCall {
  method: RestConfig['method'] | null;
  url: string | null;
  body: string | null | undefined;
  headers: Record<string, string> | null;
  timeoutSec: number | null;
  redirects: number | null;
  unresolved: string[];
}

const METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD'] as const;

/**
 * Find the first `http.*` call and resolve its arguments, following top-level
 * `const` bindings so the exported shape (url / params / body in consts) reads back.
 */
function findHttpCall(ast: ESTree.Program, source: string): HttpCall | null {
  const consts = topLevelConsts(ast);
  let found: HttpCall | null = null;

  walk(ast, (node) => {
    if (found || node.type !== 'CallExpression') return;
    const call = node as ESTree.CallExpression;
    if (call.callee.type !== 'MemberExpression') return;
    const callee = call.callee;
    if (callee.object.type !== 'Identifier' || callee.object.name !== 'http') return;
    if (callee.property.type !== 'Identifier') return;

    const fn = callee.property.name;
    const unresolved: string[] = [];
    let method: RestConfig['method'] | null = null;
    let argIndex = 0;

    if (fn === 'request') {
      const v = resolve(call.arguments[0], consts);
      const s = asString(v)?.toUpperCase();
      method = (METHODS as readonly string[]).includes(s ?? '') ? (s as RestConfig['method']) : null;
      if (!method) unresolved.push('method');
      argIndex = 1;
    } else {
      const s = fn.toUpperCase();
      if (!(METHODS as readonly string[]).includes(s)) return;
      method = s as RestConfig['method'];
    }

    const urlVal = resolve(call.arguments[argIndex], consts);
    const url = asString(urlVal);
    if (!url) unresolved.push('url');

    // http.get(url, params) but http.post(url, body, params)
    const bodyless = method === 'GET' || method === 'HEAD';
    let body: string | null | undefined;
    let paramsNode: ESTree.AnyNode | undefined;

    if (fn === 'request') {
      body = readBody(call.arguments[argIndex + 1], consts, unresolved);
      paramsNode = call.arguments[argIndex + 2] as ESTree.AnyNode | undefined;
    } else if (bodyless) {
      paramsNode = call.arguments[argIndex + 1] as ESTree.AnyNode | undefined;
    } else {
      body = readBody(call.arguments[argIndex + 1], consts, unresolved);
      paramsNode = call.arguments[argIndex + 2] as ESTree.AnyNode | undefined;
    }

    const params = asRecord(resolve(paramsNode, consts));
    const headers = params ? stringRecord(asRecord(params.headers)) : null;
    const timeoutSec = params ? toSeconds(params.timeout) : null;
    const redirects = params ? asNumber(params.redirects) : null;

    found = { method, url, body, headers, timeoutSec, redirects, unresolved };
  });

  void source;
  return found;
}

function readBody(
  node: ESTree.AnyNode | undefined,
  consts: Map<string, ESTree.AnyNode>,
  unresolved: string[],
): string | null | undefined {
  if (!node) return undefined;
  const v = resolve(node, consts);
  if (v === UNRESOLVED) { unresolved.push('body'); return undefined; }
  if (v === null) return null;
  if (typeof v === 'string') return v;
  // An object body is what http.post(url, {a:1}) means — keep it as JSON text.
  return JSON.stringify(v);
}

function topLevelConsts(ast: ESTree.Program): Map<string, ESTree.AnyNode> {
  const out = new Map<string, ESTree.AnyNode>();
  const visit = (decl: ESTree.VariableDeclaration): void => {
    for (const d of decl.declarations) {
      if (d.id.type === 'Identifier' && d.init) out.set(d.id.name, d.init as ESTree.AnyNode);
    }
  };
  for (const node of ast.body) {
    if (node.type === 'VariableDeclaration') visit(node);
    else if (node.type === 'ExportNamedDeclaration' && node.declaration?.type === 'VariableDeclaration') {
      visit(node.declaration);
    }
  }
  return out;
}

/** staticValue, but an Identifier is looked up in top-level consts first. */
function resolve(
  node: ESTree.AnyNode | undefined,
  consts: Map<string, ESTree.AnyNode>,
  depth = 0,
): Static | typeof UNRESOLVED {
  if (!node) return UNRESOLVED;
  if (node.type === 'Identifier' && depth < 5) {
    const target = consts.get(node.name);
    return target ? resolve(target, consts, depth + 1) : UNRESOLVED;
  }
  return staticValue(node);
}

function stringRecord(rec: Record<string, Static> | null): Record<string, string> | null {
  if (!rec) return null;
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(rec)) {
    if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') out[k] = String(v);
  }
  return out;
}

function findSleepSeconds(ast: ESTree.Program): number | null {
  let secs: number | null = null;
  walk(ast, (node) => {
    if (secs !== null || node.type !== 'CallExpression') return;
    const call = node as ESTree.CallExpression;
    if (call.callee.type !== 'Identifier' || call.callee.name !== 'sleep') return;
    const v = asNumber(staticValue(call.arguments[0] as ESTree.AnyNode));
    if (v !== null) secs = v;
  });
  return secs;
}

interface CheckParse { checks: CheckSpec[]; warnings: string[] }

/** Read `check(res, { 'name': (r) => <expr> })` and classify recognised predicates. */
function parseChecks(ast: ESTree.Program, source: string): CheckParse {
  const checks: CheckSpec[] = [];
  const warnings: string[] = [];

  walk(ast, (node) => {
    if (node.type !== 'CallExpression') return;
    const call = node as ESTree.CallExpression;
    if (call.callee.type !== 'Identifier' || call.callee.name !== 'check') return;
    const obj = call.arguments[1];
    if (!obj || obj.type !== 'ObjectExpression') return;

    for (const prop of (obj as ESTree.ObjectExpression).properties) {
      if (prop.type !== 'Property') continue;
      const name = propertyName(prop);
      if (!name) continue;
      const fn = prop.value;
      if (fn.type !== 'ArrowFunctionExpression' && fn.type !== 'FunctionExpression') continue;
      const bodyNode = fn.type === 'ArrowFunctionExpression' && fn.body.type !== 'BlockStatement'
        ? fn.body
        : returnedExpression(fn.body as ESTree.BlockStatement);
      if (!bodyNode) { warnings.push(`check "${name}" has no single return expression — kept as latency check`); continue; }

      const spec = classifyPredicate(name, bodyNode as ESTree.AnyNode);
      if (spec) {
        checks.push(spec);
      } else {
        warnings.push(`check "${name}" uses a predicate the form cannot represent: ${snippet(source, bodyNode as ESTree.AnyNode)}`);
      }
    }
  });

  return { checks, warnings };
}

function returnedExpression(block: ESTree.BlockStatement): ESTree.AnyNode | null {
  for (const st of block.body) {
    if (st.type === 'ReturnStatement' && st.argument) return st.argument as ESTree.AnyNode;
  }
  return null;
}

/**
 * Recognise both the shapes this exporter writes and the idioms people actually
 * type by hand (`r.status === 200`, `r.status >= 200 && r.status < 300`).
 */
function classifyPredicate(name: string, node: ESTree.AnyNode): CheckSpec | null {
  // matchStatus(r.status, '200|201')
  if (node.type === 'CallExpression') {
    const call = node as ESTree.CallExpression;
    if (call.callee.type === 'Identifier' && call.callee.name === 'matchStatus') {
      const v = asString(staticValue(call.arguments[1] as ESTree.AnyNode));
      if (v) return { name, kind: 'status', value: v, minPassRatePct: 100 };
    }
    // String(r.body || '').includes('needle')
    if (call.callee.type === 'MemberExpression' && call.callee.property.type === 'Identifier'
      && call.callee.property.name === 'includes') {
      const v = asString(staticValue(call.arguments[0] as ESTree.AnyNode));
      if (v) return { name, kind: 'body_contains', value: v, minPassRatePct: 100 };
    }
    // new RegExp('x').test(...)
    if (call.callee.type === 'MemberExpression' && call.callee.property.type === 'Identifier'
      && call.callee.property.name === 'test' && call.callee.object.type === 'NewExpression') {
      const re = call.callee.object as ESTree.NewExpression;
      const v = asString(staticValue(re.arguments[0] as ESTree.AnyNode));
      if (v) return { name, kind: 'regex', value: v, minPassRatePct: 100 };
    }
  }

  if (node.type === 'BinaryExpression') {
    const bin = node as ESTree.BinaryExpression;
    const left = bin.left as ESTree.AnyNode;
    const right = staticValue(bin.right as ESTree.AnyNode);

    // String(jsonPath(r.json(), 'a.b')) === 'value'
    const jp = findJsonPathCall(left);
    if (jp && (bin.operator === '===' || bin.operator === '==') && typeof right === 'string') {
      return { name, kind: 'json_path', value: right, path: jp, minPassRatePct: 100 };
    }
    // r.timings.duration < 500
    if (isMemberPath(left, ['r', 'timings', 'duration']) && (bin.operator === '<' || bin.operator === '<=')
      && typeof right === 'number') {
      return { name, kind: 'latency_under', value: String(right), minPassRatePct: 100 };
    }
    // r.status === 200
    if (isMemberPath(left, ['r', 'status']) && (bin.operator === '===' || bin.operator === '==')
      && typeof right === 'number') {
      return { name, kind: 'status', value: String(right), minPassRatePct: 100 };
    }
  }

  // r.status >= 200 && r.status < 300  →  a range
  if (node.type === 'LogicalExpression' && (node as ESTree.LogicalExpression).operator === '&&') {
    const log = node as ESTree.LogicalExpression;
    const lo = statusBound(log.left as ESTree.AnyNode);
    const hi = statusBound(log.right as ESTree.AnyNode);
    if (lo && hi && lo.dir === 'min' && hi.dir === 'max') {
      return { name, kind: 'status', value: `${lo.value}-${hi.value}`, minPassRatePct: 100 };
    }
  }
  return null;
}

function statusBound(node: ESTree.AnyNode): { dir: 'min' | 'max'; value: number } | null {
  if (node.type !== 'BinaryExpression') return null;
  const bin = node as ESTree.BinaryExpression;
  if (!isMemberPath(bin.left as ESTree.AnyNode, ['r', 'status'])) return null;
  const v = asNumber(staticValue(bin.right as ESTree.AnyNode));
  if (v === null) return null;
  if (bin.operator === '>=') return { dir: 'min', value: v };
  if (bin.operator === '>') return { dir: 'min', value: v + 1 };
  if (bin.operator === '<') return { dir: 'max', value: v - 1 };
  if (bin.operator === '<=') return { dir: 'max', value: v };
  return null;
}

function findJsonPathCall(node: ESTree.AnyNode): string | null {
  let path: string | null = null;
  walk({ type: 'Program', body: [{ type: 'ExpressionStatement', expression: node } as never], sourceType: 'module' } as unknown as ESTree.Program, (n) => {
    if (path || n.type !== 'CallExpression') return;
    const call = n as ESTree.CallExpression;
    if (call.callee.type === 'Identifier' && call.callee.name === 'jsonPath') {
      path = asString(staticValue(call.arguments[1] as ESTree.AnyNode));
    }
  });
  return path;
}

function isMemberPath(node: ESTree.AnyNode, path: string[]): boolean {
  const parts: string[] = [];
  let cur: ESTree.AnyNode | null = node;
  while (cur) {
    if (cur.type === 'MemberExpression') {
      const m = cur as ESTree.MemberExpression;
      if (m.computed || m.property.type !== 'Identifier') return false;
      parts.unshift(m.property.name);
      cur = m.object as ESTree.AnyNode;
    } else if (cur.type === 'Identifier') {
      parts.unshift((cur as ESTree.Identifier).name);
      break;
    } else {
      return false;
    }
  }
  // The callback parameter is not always named `r`; compare the tail only.
  return parts.length === path.length && parts.slice(1).join('.') === path.slice(1).join('.');
}

function snippet(source: string, node: ESTree.AnyNode): string {
  const text = source.slice(node.start, node.end).replace(/\s+/g, ' ');
  return text.length > 70 ? `${text.slice(0, 70)}…` : text;
}

/** Minimal recursive AST walk — avoids pulling in acorn-walk for one traversal. */
function walk(node: unknown, visit: (n: ESTree.AnyNode) => void): void {
  if (!node || typeof node !== 'object') return;
  if (Array.isArray(node)) {
    for (const child of node) walk(child, visit);
    return;
  }
  const n = node as Record<string, unknown>;
  if (typeof n.type === 'string') visit(node as ESTree.AnyNode);
  for (const key of Object.keys(n)) {
    if (key === 'type' || key === 'start' || key === 'end' || key === 'loc') continue;
    walk(n[key], visit);
  }
}

// ─── Formatting ──────────────────────────────────────────────────────────────

function str(s: string): string {
  return JSON.stringify(s);
}

function json(value: unknown, indent: number): string {
  const text = JSON.stringify(value, null, 2);
  return indent === 0 ? text : text.split('\n').map((l, i) => (i === 0 ? l : '  '.repeat(indent) + l)).join('\n');
}

function hasHeader(headers: Record<string, string>, name: string): boolean {
  return Object.keys(headers).some((k) => k.toLowerCase() === name.toLowerCase());
}

function looksJson(body: string): boolean {
  const t = body.trim();
  return (t.startsWith('{') && t.endsWith('}')) || (t.startsWith('[') && t.endsWith(']'));
}

function round4(n: number): number { return Math.round(n * 10000) / 10000; }

void parseThreshold;
