import { parse as yamlParse, stringify as yamlStringify } from 'yaml';
import { DEFAULT_KAFKA } from '../shared/defaults.ts';
import { parseThreshold } from '../metrics/thresholds.ts';
import type { CheckSpec, KafkaConfig, RunConfig, ThresholdSpec } from '../shared/types.ts';
import type { ImportResult } from './k6.ts';

/**
 * Kafka has no standard load-test script format, so the portable form is a
 * declarative YAML document that maps one-to-one onto the UI. It round-trips
 * exactly, and unlike a JS generator it carries no executable code.
 */

export function toKafkaScript(config: RunConfig): string {
  const k = config.kafka ?? DEFAULT_KAFKA;
  const doc = {
    protocol: 'kafka',
    broker: {
      bootstrapServers: k.bootstrapServers,
      topic: k.topic,
      acks: k.acks,
      compression: k.compression,
      // Raw librdkafka properties override everything above.
      librdkafka: k.librdkafka,
    },
    load: {
      producers: k.producers,
      targetRate: k.targetRate,
      durationSec: k.durationSec,
      maxMessages: k.maxMessages,
    },
    message: {
      keyStrategy: k.keyStrategy,
      keyValue: k.keyValue,
      payloadType: k.payloadType,
      payloadSizeBytes: k.payloadSizeBytes,
      payload: k.payload,
    },
    latency: {
      mode: k.latencyMode,
      consumerGroup: k.consumerGroup,
      monitorLag: k.monitorLag,
    },
    checks: config.checks,
    thresholds: config.thresholds.map((t) => t.expr),
  };
  return [
    '# Generated by Loadtest Dashboard — edit freely and import it back.',
    '# Placeholders available in `payload`: {{seq}}, {{ts}}, {{uuid}}',
    yamlStringify(doc),
  ].join('\n');
}

export function fromKafkaScript(source: string): ImportResult {
  const warnings: string[] = [];
  let doc: Record<string, unknown> | null;
  try {
    doc = yamlParse(source) as Record<string, unknown> | null;
  } catch (err) {
    throw new Error(`not parseable YAML or JSON: ${(err as Error).message}`);
  }
  if (!doc || typeof doc !== 'object') throw new Error('document is empty');

  const k: KafkaConfig = structuredClone(DEFAULT_KAFKA);
  // Accept both the nested shape written above and a flat one someone may hand-write.
  const broker = rec(doc.broker) ?? doc;
  const load = rec(doc.load) ?? doc;
  const message = rec(doc.message) ?? doc;
  const latency = rec(doc.latency) ?? doc;

  const bs = str(broker.bootstrapServers) ?? str(broker['bootstrap.servers']);
  if (bs) k.bootstrapServers = bs; else warnings.push('no bootstrapServers — left at default');

  const topic = str(broker.topic);
  if (topic) k.topic = topic; else warnings.push('no topic — left at default');

  const acks = str(broker.acks) ?? (num(broker.acks) !== null ? String(num(broker.acks)) : null);
  if (acks === '0' || acks === '1' || acks === 'all' || acks === '-1') k.acks = acks === '-1' ? 'all' : acks;
  else if (acks !== null) warnings.push(`acks "${acks}" is not 0, 1 or all — left at default`);

  const comp = str(broker.compression);
  if (comp && ['none', 'gzip', 'snappy', 'lz4', 'zstd'].includes(comp)) k.compression = comp as KafkaConfig['compression'];
  else if (comp) warnings.push(`compression "${comp}" unknown — left at default`);

  const rd = strRecord(rec(broker.librdkafka));
  if (rd) k.librdkafka = rd;

  k.producers = clamp(num(load.producers), 1, 64) ?? k.producers;
  k.targetRate = clamp(num(load.targetRate), 1, 1_000_000) ?? k.targetRate;
  k.durationSec = clamp(num(load.durationSec), 1, 86_400) ?? k.durationSec;
  k.maxMessages = clamp(num(load.maxMessages), 0, Number.MAX_SAFE_INTEGER) ?? k.maxMessages;

  const keyStrategy = str(message.keyStrategy);
  if (keyStrategy && ['none', 'random', 'fixed', 'sequence'].includes(keyStrategy)) {
    k.keyStrategy = keyStrategy as KafkaConfig['keyStrategy'];
  } else if (keyStrategy) warnings.push(`keyStrategy "${keyStrategy}" unknown — left at default`);
  k.keyValue = str(message.keyValue) ?? k.keyValue;

  const payloadType = str(message.payloadType);
  if (payloadType && ['json', 'raw', 'random'].includes(payloadType)) {
    k.payloadType = payloadType as KafkaConfig['payloadType'];
  } else if (payloadType) warnings.push(`payloadType "${payloadType}" unknown — left at default`);
  k.payloadSizeBytes = clamp(num(message.payloadSizeBytes), 1, 10_000_000) ?? k.payloadSizeBytes;
  const payload = message.payload;
  if (typeof payload === 'string') k.payload = payload;
  else if (payload && typeof payload === 'object') k.payload = JSON.stringify(payload);

  const mode = str(latency.mode) ?? str(latency.latencyMode);
  if (mode === 'produce-ack' || mode === 'end-to-end') k.latencyMode = mode;
  else if (mode) warnings.push(`latency mode "${mode}" unknown — left at default`);
  k.consumerGroup = str(latency.consumerGroup) ?? k.consumerGroup;
  if (typeof latency.monitorLag === 'boolean') k.monitorLag = latency.monitorLag;

  const checks: CheckSpec[] = [];
  for (const raw of arr(doc.checks) ?? []) {
    const c = rec(raw);
    const name = str(c?.name);
    if (!c || !name) continue;
    const kind = str(c.kind);
    // Kafka has no response body — only latency checks are meaningful here.
    if (kind !== 'latency_under') {
      warnings.push(`check "${name}" of kind "${kind ?? '?'}" does not apply to Kafka — dropped`);
      continue;
    }
    checks.push({
      name, kind: 'latency_under',
      value: str(c.value) ?? String(num(c.value) ?? ''),
      minPassRatePct: num(c.minPassRatePct) ?? undefined,
    });
  }

  const thresholds: ThresholdSpec[] = [];
  for (const e of arr(doc.thresholds) ?? []) {
    if (typeof e !== 'string') continue;
    if (parseThreshold(e)) thresholds.push({ expr: e });
    else warnings.push(`threshold "${e}" is not valid DSL — dropped`);
  }

  return {
    config: { protocol: 'kafka', kafka: k, checks, thresholds, script: { mode: 'builtin', content: '', path: '', filename: '' } },
    warnings,
  };
}

function rec(v: unknown): Record<string, unknown> | null {
  return v && typeof v === 'object' && !Array.isArray(v) ? (v as Record<string, unknown>) : null;
}
function arr(v: unknown): unknown[] | null { return Array.isArray(v) ? v : null; }
function str(v: unknown): string | null { return typeof v === 'string' ? v : null; }
function num(v: unknown): number | null {
  if (typeof v === 'number' && Number.isFinite(v)) return v;
  if (typeof v === 'string' && v.trim() !== '' && Number.isFinite(Number(v))) return Number(v);
  return null;
}
function clamp(v: number | null, lo: number, hi: number): number | null {
  return v === null ? null : Math.min(Math.max(Math.round(v), lo), hi);
}
function strRecord(r: Record<string, unknown> | null): Record<string, string> | null {
  if (!r) return null;
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(r)) {
    if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') out[k] = String(v);
  }
  return out;
}
